#spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ocpp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
#    username: ${SPRING_DATASOURCE_USERNAME:ocpp}
#    password: ${SPRING_DATASOURCE_PASSWORD:ocpppw}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=ocppdb;encrypt=true;trustServerCertificate=false;}
    username: ${SPRING_DATASOURCE_USERNAME:ocppadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:CXZdsa@12}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.web.socket: INFO
    root: INFO			